environment:
  PYTHON: "C:\\Python37"
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: "32"
  TWINE_USERNAME:
    secure: yig0ualP0M39xIahEXhxZA==
  TWINE_PASSWORD:
    secure: 79wxWyPcqzj6131wKAuWBg==
  DOCKER_USERNAME:
    secure: yig0ualP0M39xIahEXhxZA==
  DOCKER_PASSWORD:
    secure: uiu9FbvYYz89WrBtF6BN0w==
  AWS_ACCESS_KEY_ID:
    secure: ED96t0LSsl1VnMu5CEQddJYdsIwIdsomF6gmY7r49w8=
  AWS_SECRET_ACCESS_KEY:
    secure: r/GpKgKWeTtq2k2J+Wy4qwOvLa8auzCgSYvEb88NqzenKZh04wUiWyxwXk6xc7UV

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip setuptools"
  - "pip install -r requirements-dev.txt -r requirements.txt"
  - "pip install awscli backports-datetime-fromisoformat"
  - "git describe --tags --dirty --always"

test_script:
  - "pip install -e ."


after_test:
  - "mkdir svtplay-dl"
  - "python setversion.py"
  - "python setup.py build_exe"
  - "dir /s build"
  - "build\\exe.win32-3.7\\svtplay-dl.exe --version"
  - "xcopy /s build\\exe.win32-3.7 svtplay-dl"
  - "7z.exe a -tzip svtplay-dl.zip svtplay-dl"
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" python scripts/cibuild.py

artifacts:
  - path: svtplay-dl.zip
    name: svtplay-dl

build: off
